[package]
name = "e07_returning_impl_traits"
version = "0.1.0"
authors = ["Dominic Torruellas <dom@domtorr.com>"]
edition = "2018"

[lib]
name = "aggregator"
path = "src/lib.rs"

[[bin]]
name = "aggregator"
path = "src/main.rs"

[dependencies]
